export interface Player {
  id: string
  name: string
  description: string
  image: string
  team: string
  country: string
  careerSpan: string
  rating: number
  stats: Record<string, string>
  highlights: string
}

export interface Device {
  id: string
  name: string
  description: string
  image: string
  specs: Record<string, string>
  price: number
  rating: number
}

export const batters: Player[] = [
  {
    id: "batter-1",
    name: "Virat Kohli",
    description: "The run machine and former RCB captain with the most runs in IPL history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Royal Challengers Bangalore",
    country: "India",
    careerSpan: "2008-Present",
    rating: 9.8,
    stats: {
      Runs: "7263",
      Average: "37.24",
      "Strike Rate": "130.02",
      Centuries: "7",
      "Half Centuries": "50",
      "Highest Score": "113",
      Fours: "643",
      Sixes: "234",
      Matches: "237",
    },
    highlights: "Most runs in IPL history, most centuries, and highest individual score by an Indian batsman.",
  },
  {
    id: "batter-2",
    name: "Rohit Sharma",
    description: "Mumbai Indians' captain and one of the most successful leaders in IPL history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "India",
    careerSpan: "2008-Present",
    rating: 9.5,
    stats: {
      Runs: "6211",
      Average: "30.05",
      "Strike Rate": "130.54",
      Centuries: "1",
      "Half Centuries": "42",
      "Highest Score": "109*",
      Fours: "555",
      Sixes: "257",
      Matches: "243",
    },
    highlights: "Led Mumbai Indians to 5 IPL titles, most by any captain. Known for his elegant batting style.",
  },
  {
    id: "batter-3",
    name: "AB de Villiers",
    description: "Mr. 360° - known for his innovative shots and explosive batting.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Royal Challengers Bangalore",
    country: "South Africa",
    careerSpan: "2008-2021",
    rating: 9.7,
    stats: {
      Runs: "5162",
      Average: "39.71",
      "Strike Rate": "151.69",
      Centuries: "3",
      "Half Centuries": "40",
      "Highest Score": "133*",
      Fours: "413",
      Sixes: "251",
      Matches: "184",
    },
    highlights: "Holds the record for the fastest IPL fifty (17 balls) and fastest IPL hundred (31 balls).",
  },
  {
    id: "batter-4",
    name: "David Warner",
    description: "Explosive opener and consistent run-scorer with three Orange Caps.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Delhi Capitals",
    country: "Australia",
    careerSpan: "2009-Present",
    rating: 9.4,
    stats: {
      Runs: "6201",
      Average: "41.61",
      "Strike Rate": "139.97",
      Centuries: "4",
      "Half Centuries": "57",
      "Highest Score": "126",
      Fours: "578",
      Sixes: "223",
      Matches: "176",
    },
    highlights:
      "Only player to win the Orange Cap three times. Led Sunrisers Hyderabad to their only IPL title in 2016.",
  },
  {
    id: "batter-5",
    name: "Chris Gayle",
    description: "The Universe Boss - the most destructive batsman in T20 cricket history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Punjab Kings",
    country: "West Indies",
    careerSpan: "2009-2021",
    rating: 9.6,
    stats: {
      Runs: "4965",
      Average: "39.72",
      "Strike Rate": "148.96",
      Centuries: "6",
      "Half Centuries": "31",
      "Highest Score": "175*",
      Fours: "405",
      Sixes: "357",
      Matches: "142",
    },
    highlights: "Holds the record for the highest individual score in IPL (175*) and most sixes in IPL history.",
  },
  {
    id: "batter-6",
    name: "Suresh Raina",
    description: "Mr. IPL - one of the most consistent performers in the tournament's history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "India",
    careerSpan: "2008-2021",
    rating: 9.2,
    stats: {
      Runs: "5528",
      Average: "32.52",
      "Strike Rate": "136.73",
      Centuries: "1",
      "Half Centuries": "39",
      "Highest Score": "100*",
      Fours: "506",
      Sixes: "203",
      Matches: "205",
    },
    highlights: "Second highest run-scorer in IPL history for many years. Integral part of CSK's multiple title wins.",
  },
  {
    id: "batter-7",
    name: "MS Dhoni",
    description: "Captain Cool - the most successful captain and finisher in IPL history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "India",
    careerSpan: "2008-Present",
    rating: 9.5,
    stats: {
      Runs: "5082",
      Average: "39.09",
      "Strike Rate": "135.92",
      "Half Centuries": "24",
      "Highest Score": "84*",
      Fours: "346",
      Sixes: "239",
      Matches: "250",
    },
    highlights: "Led CSK to 5 IPL titles. Known for his finishing abilities and lightning-fast wicketkeeping.",
  },
  {
    id: "batter-8",
    name: "Shikhar Dhawan",
    description: "Gabbar - consistent opener with elegant stroke play.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Punjab Kings",
    country: "India",
    careerSpan: "2008-Present",
    rating: 8.9,
    stats: {
      Runs: "6617",
      Average: "35.38",
      "Strike Rate": "127.61",
      Centuries: "2",
      "Half Centuries": "49",
      "Highest Score": "106*",
      Fours: "730",
      Sixes: "147",
      Matches: "217",
    },
    highlights: "Second highest run-scorer in IPL history. Known for his consistency at the top of the order.",
  },
  {
    id: "batter-9",
    name: "Jos Buttler",
    description: "Explosive wicketkeeper-batsman with incredible range of shots.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Rajasthan Royals",
    country: "England",
    careerSpan: "2016-Present",
    rating: 9.3,
    stats: {
      Runs: "3223",
      Average: "39.78",
      "Strike Rate": "148.31",
      Centuries: "6",
      "Half Centuries": "18",
      "Highest Score": "124",
      Fours: "290",
      Sixes: "154",
      Matches: "96",
    },
    highlights: "Scored 4 centuries in a single IPL season (2022). Orange Cap winner in 2022.",
  },
  {
    id: "batter-10",
    name: "KL Rahul",
    description: "Elegant batsman with consistent performances across seasons.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Lucknow Super Giants",
    country: "India",
    careerSpan: "2013-Present",
    rating: 9.0,
    stats: {
      Runs: "4163",
      Average: "46.78",
      "Strike Rate": "134.53",
      Centuries: "4",
      "Half Centuries": "33",
      "Highest Score": "132*",
      Fours: "361",
      Sixes: "184",
      Matches: "118",
    },
    highlights:
      "Scored 600+ runs in three consecutive IPL seasons (2018, 2019, 2020). Known for his classical technique.",
  },
]

export const bowlers: Player[] = [
  {
    id: "bowler-1",
    name: "Yuzvendra Chahal",
    description: "Crafty leg-spinner with the most wickets in IPL history.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Rajasthan Royals",
    country: "India",
    careerSpan: "2013-Present",
    rating: 9.5,
    stats: {
      Wickets: "187",
      Economy: "7.67",
      Average: "21.68",
      "Best Figures": "5/40",
      "Strike Rate": "16.96",
      "4+ Wickets": "5",
      "Dot Ball %": "36.2%",
      Matches: "143",
    },
    highlights: "Highest wicket-taker in IPL history. First bowler to take a hat-trick in IPL 2022.",
  },
  {
    id: "bowler-2",
    name: "Lasith Malinga",
    description: "Yorker specialist with the most lethal bowling action in IPL.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "Sri Lanka",
    careerSpan: "2009-2019",
    rating: 9.7,
    stats: {
      Wickets: "170",
      Economy: "7.14",
      Average: "19.80",
      "Best Figures": "5/13",
      "Strike Rate": "16.62",
      "4+ Wickets": "6",
      "Dot Ball %": "41.8%",
      Matches: "122",
    },
    highlights:
      "Bowled the final over in multiple IPL finals, securing victories for Mumbai Indians. Known for his yorkers.",
  },
  {
    id: "bowler-3",
    name: "Jasprit Bumrah",
    description: "India's premier fast bowler with an unorthodox action and pinpoint yorkers.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "India",
    careerSpan: "2013-Present",
    rating: 9.6,
    stats: {
      Wickets: "145",
      Economy: "7.39",
      Average: "23.30",
      "Best Figures": "5/10",
      "Strike Rate": "18.90",
      "4+ Wickets": "2",
      "Dot Ball %": "43.2%",
      Matches: "120",
    },
    highlights:
      "Known for his death bowling expertise and ability to bowl yorkers at will. Crucial to Mumbai Indians' success.",
  },
  {
    id: "bowler-4",
    name: "Sunil Narine",
    description: "Mystery spinner who revolutionized T20 bowling with his variations.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Kolkata Knight Riders",
    country: "West Indies",
    careerSpan: "2012-Present",
    rating: 9.4,
    stats: {
      Wickets: "163",
      Economy: "6.67",
      Average: "25.31",
      "Best Figures": "5/19",
      "Strike Rate": "22.74",
      "4+ Wickets": "4",
      "Dot Ball %": "40.1%",
      Matches: "162",
    },
    highlights:
      "Best economy rate among bowlers with 100+ wickets. Has reinvented himself multiple times throughout his career.",
  },
  {
    id: "bowler-5",
    name: "Bhuvneshwar Kumar",
    description: "Swing bowling specialist who excels in the powerplay overs.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Sunrisers Hyderabad",
    country: "India",
    careerSpan: "2011-Present",
    rating: 9.0,
    stats: {
      Wickets: "170",
      Economy: "7.31",
      Average: "26.05",
      "Best Figures": "5/19",
      "Strike Rate": "21.37",
      "4+ Wickets": "3",
      "Dot Ball %": "38.7%",
      Matches: "159",
    },
    highlights: "Two-time Purple Cap winner (2016, 2017). Known for his ability to swing the new ball both ways.",
  },
  {
    id: "bowler-6",
    name: "Rashid Khan",
    description: "Afghan leg-spinner with a lightning-quick arm action and deadly googlies.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Gujarat Titans",
    country: "Afghanistan",
    careerSpan: "2017-Present",
    rating: 9.5,
    stats: {
      Wickets: "129",
      Economy: "6.66",
      Average: "21.63",
      "Best Figures": "4/24",
      "Strike Rate": "19.48",
      "4+ Wickets": "1",
      "Dot Ball %": "42.3%",
      Matches: "109",
    },
    highlights:
      "Best economy rate in IPL history among bowlers with 100+ wickets. Impossible to hit even when batsmen know what's coming.",
  },
  {
    id: "bowler-7",
    name: "Dwayne Bravo",
    description: "Death bowling specialist with clever variations and slower balls.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "West Indies",
    careerSpan: "2008-2022",
    rating: 9.1,
    stats: {
      Wickets: "183",
      Economy: "8.38",
      Average: "23.82",
      "Best Figures": "4/22",
      "Strike Rate": "17.04",
      "4+ Wickets": "2",
      "Dot Ball %": "35.6%",
      Matches: "161",
    },
    highlights: "Former highest wicket-taker in IPL history. Master of the slower ball and death bowling specialist.",
  },
  {
    id: "bowler-8",
    name: "Harbhajan Singh",
    description: "Experienced off-spinner with excellent control and variations.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "India",
    careerSpan: "2008-2021",
    rating: 8.9,
    stats: {
      Wickets: "150",
      Economy: "7.05",
      Average: "26.86",
      "Best Figures": "5/18",
      "Strike Rate": "22.84",
      "4+ Wickets": "2",
      "Dot Ball %": "37.8%",
      Matches: "163",
    },
    highlights:
      "Key member of Mumbai Indians' title-winning campaigns. Known for his ability to bowl in the powerplay.",
  },
  {
    id: "bowler-9",
    name: "Amit Mishra",
    description: "Classical leg-spinner with a deceptive googly and flight.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Delhi Capitals",
    country: "India",
    careerSpan: "2008-2022",
    rating: 8.8,
    stats: {
      Wickets: "166",
      Economy: "7.35",
      Average: "23.97",
      "Best Figures": "5/17",
      "Strike Rate": "19.55",
      "4+ Wickets": "4",
      "Dot Ball %": "36.9%",
      Matches: "154",
    },
    highlights:
      "Only bowler to take three hat-tricks in IPL history. One of the most successful leg-spinners in the tournament.",
  },
  {
    id: "bowler-10",
    name: "Ravichandran Ashwin",
    description: "Innovative off-spinner who constantly evolves his bowling arsenal.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Rajasthan Royals",
    country: "India",
    careerSpan: "2009-Present",
    rating: 9.0,
    stats: {
      Wickets: "157",
      Economy: "7.04",
      Average: "28.56",
      "Best Figures": "4/34",
      "Strike Rate": "24.31",
      "4+ Wickets": "1",
      "Dot Ball %": "38.2%",
      Matches: "191",
    },
    highlights: "Led Kings XI Punjab as captain. Known for his innovative variations and tactical acumen.",
  },
]

export const allrounders: Player[] = [
  {
    id: "allrounder-1",
    name: "Andre Russell",
    description: "Explosive West Indian all-rounder known for his power hitting and pace bowling.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Kolkata Knight Riders",
    country: "West Indies",
    careerSpan: "2012-Present",
    rating: 9.6,
    stats: {
      "Batting Average": "30.40",
      "Batting SR": "179.70",
      Runs: "2262",
      Sixes: "189",
      "Bowling Economy": "9.13",
      Wickets: "96",
      "Best Bowling": "5/15",
      Matches: "113",
    },
    highlights:
      "Most Valuable Player award winner multiple times. Can change the game with both bat and ball in a matter of overs.",
  },
  {
    id: "allrounder-2",
    name: "Hardik Pandya",
    description: "India's premier fast bowling all-rounder and Gujarat Titans' title-winning captain.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "India",
    careerSpan: "2015-Present",
    rating: 9.4,
    stats: {
      "Batting Average": "31.29",
      "Batting SR": "151.28",
      Runs: "2309",
      Sixes: "125",
      "Bowling Economy": "8.71",
      Wickets: "53",
      "Best Bowling": "3/17",
      Matches: "123",
    },
    highlights:
      "Led Gujarat Titans to IPL title in their debut season as captain. Known for his clutch performances in finals.",
  },
  {
    id: "allrounder-3",
    name: "Ravindra Jadeja",
    description: "Three-dimensional player with exceptional fielding, accurate bowling, and powerful batting.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "India",
    careerSpan: "2008-Present",
    rating: 9.3,
    stats: {
      "Batting Average": "26.61",
      "Batting SR": "135.21",
      Runs: "2692",
      Sixes: "102",
      "Bowling Economy": "7.61",
      Wickets: "152",
      "Best Bowling": "5/16",
      Matches: "226",
    },
    highlights:
      "One of the best fielders in cricket history. Consistent performer for CSK across multiple title-winning campaigns.",
  },
  {
    id: "allrounder-4",
    name: "Kieron Pollard",
    description: "Powerful West Indian all-rounder and Mumbai Indians legend.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Mumbai Indians",
    country: "West Indies",
    careerSpan: "2010-2022",
    rating: 9.2,
    stats: {
      "Batting Average": "28.67",
      "Batting SR": "147.32",
      Runs: "3412",
      Sixes: "223",
      "Bowling Economy": "8.78",
      Wickets: "69",
      "Best Bowling": "4/44",
      Matches: "189",
    },
    highlights: "Key member of Mumbai Indians' five title-winning campaigns. Known for his death batting prowess.",
  },
  {
    id: "allrounder-5",
    name: "Sunil Narine",
    description: "Mystery spinner who evolved into a dangerous pinch-hitting opener.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Kolkata Knight Riders",
    country: "West Indies",
    careerSpan: "2012-Present",
    rating: 9.3,
    stats: {
      "Batting Average": "17.55",
      "Batting SR": "161.73",
      Runs: "1144",
      Sixes: "108",
      "Bowling Economy": "6.67",
      Wickets: "163",
      "Best Bowling": "5/19",
      Matches: "162",
    },
    highlights:
      "Revolutionized the role of a spinner in T20 cricket. Later developed into a dangerous pinch-hitting opener.",
  },
  {
    id: "allrounder-6",
    name: "Shane Watson",
    description: "Powerful Australian all-rounder who dominated with both bat and ball.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "Australia",
    careerSpan: "2008-2020",
    rating: 9.1,
    stats: {
      "Batting Average": "29.15",
      "Batting SR": "137.91",
      Runs: "3874",
      Sixes: "190",
      "Bowling Economy": "7.93",
      Wickets: "92",
      "Best Bowling": "4/29",
      Matches: "145",
    },
    highlights: "Player of the Tournament in the inaugural IPL season. Scored century in 2018 IPL final for CSK.",
  },
  {
    id: "allrounder-7",
    name: "Dwayne Bravo",
    description: "Versatile all-rounder with exceptional death bowling skills.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Chennai Super Kings",
    country: "West Indies",
    careerSpan: "2008-2022",
    rating: 9.0,
    stats: {
      "Batting Average": "22.83",
      "Batting SR": "129.62",
      Runs: "1560",
      Sixes: "71",
      "Bowling Economy": "8.38",
      Wickets: "183",
      "Best Bowling": "4/22",
      Matches: "161",
    },
    highlights: "Former highest wicket-taker in IPL history. Purple Cap winner in 2013 and 2015.",
  },
  {
    id: "allrounder-8",
    name: "Glenn Maxwell",
    description: "The Big Show - explosive batting all-rounder with useful off-spin.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Royal Challengers Bangalore",
    country: "Australia",
    careerSpan: "2012-Present",
    rating: 8.9,
    stats: {
      "Batting Average": "26.41",
      "Batting SR": "154.12",
      Runs: "2719",
      Sixes: "159",
      "Bowling Economy": "8.33",
      Wickets: "34",
      "Best Bowling": "2/15",
      Matches: "124",
    },
    highlights:
      "Known for his innovative batting and ability to clear any boundary. Useful off-spinner in the middle overs.",
  },
  {
    id: "allrounder-9",
    name: "Axar Patel",
    description: "Consistent left-arm spinner who has developed into a reliable lower-order batsman.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Delhi Capitals",
    country: "India",
    careerSpan: "2013-Present",
    rating: 8.7,
    stats: {
      "Batting Average": "20.20",
      "Batting SR": "138.76",
      Runs: "1293",
      Sixes: "60",
      "Bowling Economy": "7.35",
      Wickets: "101",
      "Best Bowling": "4/21",
      Matches: "136",
    },
    highlights: "Economical bowler who has developed into a reliable finisher with the bat in recent seasons.",
  },
  {
    id: "allrounder-10",
    name: "Venkatesh Iyer",
    description: "Emerging all-rounder who made an immediate impact in the IPL.",
    image: "/placeholder.svg?height=600&width=600",
    team: "Kolkata Knight Riders",
    country: "India",
    careerSpan: "2021-Present",
    rating: 8.5,
    stats: {
      "Batting Average": "30.29",
      "Batting SR": "136.65",
      Runs: "969",
      Sixes: "45",
      "Bowling Economy": "8.84",
      Wickets: "10",
      "Best Bowling": "2/29",
      Matches: "36",
    },
    highlights: "Breakout star of IPL 2021 who helped KKR reach the final with his all-round performances.",
  },
]
